from pathlib import Path
import sys

sys.path.append(str(Path(__file__).parent.parent))

from db.database import JobDatabase


def seed_jobs():
    """Seed the db w sample jobs"""
    db = JobDatabase()

#     jobs = [
#         {
#             "title": "Senior Software Engineer",
#             "company": "TechCorp",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Senior",
#             "salary_range": "$120,000 - $180,000",
#             "description": "Lead development of cloud-native applications using modern technologies.",
#             "requirements": [
#                 "Python",
#                 "JavaScript",
#                 "React",
#                 "AWS",
#                 "Kubernetes",
#                 "5+ years experience",
#             ],
#             "benefits": [
#                 "Health insurance",
#                 "401(k) matching",
#                 "Remote work",
#                 "Learning budget",
#             ],
#         },
#         {
#             "title": "Data Scientist",
#             "company": "DataCo",
#             "location": "New York, NY",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$100,000 - $140,000",
#             "description": "Build and deploy machine learning models for predictive analytics.",
#             "requirements": [
#                 "Python",
#                 "SQL",
#                 "Machine Learning",
#                 "Statistics",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "Stock options", "Flexible hours"],
#         },
#         {
#             "title": "Frontend Developer",
#             "company": "WebTech",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$90,000 - $130,000",
#             "description": "Create responsive web applications using modern frontend technologies.",
#             "requirements": [
#                 "JavaScript",
#                 "TypeScript",
#                 "React",
#                 "CSS",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "Remote work", "Professional development"],
#         },
#         {
#             "title": "Project Manager",
#             "company": "BizGroup",
#             "location": "San Francisco, CA",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$80,000 - $110,000",
#             "description": "Manage multiple projects and coordinate with cross-functional teams.",
#             "requirements": [
#                 "Project management",
#                 "Agile methodologies",
#                 "Communication skills",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "401(k)", "Paid time off"],
#         },
#         {
#             "title": "Graphic Designer",
#             "company": "DesignCo",
#             "location": "Austin, TX",
#             "type": "Part-time",
#             "experience_level": "Entry-level",
#             "salary_range": "$40,000 - $60,000",
#             "description": "Design marketing materials and digital content for clients.",
#             "requirements": [
#                 "Adobe Creative Suite",
#                 "Illustration skills",
#                 "Creativity",
#                 "1+ year experience",
#             ],
#             "benefits": ["Flexible schedule", "Remote options"],
#         },
#         {
#             "title": "Marketing Specialist",
#             "company": "MarketMasters",
#             "location": "Chicago, IL",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$70,000 - $90,000",
#             "description": "Develop and implement marketing campaigns for various products.",
#             "requirements": [
#                 "SEO",
#                 "Content marketing",
#                 "Google Analytics",
#                 "2+ years experience",
#             ],
#             "benefits": [
#                 "Health insurance",
#                 "Paid vacation",
#                 "Professional development",
#             ],
#         },
#         {
#             "title": "Customer Support Representative",
#             "company": "SupportHub",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Entry-level",
#             "salary_range": "$35,000 - $50,000",
#             "description": "Assist customers with inquiries and resolve technical issues.",
#             "requirements": [
#                 "Customer service skills",
#                 "Basic technical troubleshooting",
#                 "Strong communication",
#             ],
#             "benefits": ["Remote work", "Health insurance", "Paid training"],
#         },
#         {
#             "title": "Cybersecurity Analyst",
#             "company": "SecureIT",
#             "location": "Washington, DC",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$95,000 - $130,000",
#             "description": "Monitor and respond to security incidents and protect company data.",
#             "requirements": [
#                 "Cybersecurity certifications (CISSP, CEH)",
#                 "Network security",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "401(k)", "Professional development"],
#         },
#         {
#             "title": "HR Coordinator",
#             "company": "PeopleFirst",
#             "location": "Boston, MA",
#             "type": "Full-time",
#             "experience_level": "Entry-level",
#             "salary_range": "$45,000 - $60,000",
#             "description": "Support HR functions including recruitment, onboarding, and employee relations.",
#             "requirements": [
#                 "HR experience",
#                 "Communication skills",
#                 "Organizational skills",
#                 "1+ year experience",
#             ],
#             "benefits": ["Health insurance", "Paid time off", "Retirement plan"],
#         },
#         {
#             "title": "Mechanical Engineer",
#             "company": "BuildWorks",
#             "location": "Houston, TX",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$85,000 - $120,000",
#             "description": "Design and test mechanical components for manufacturing.",
#             "requirements": [
#                 "CAD software",
#                 "Mechanical design",
#                 "Manufacturing experience",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "Paid vacation", "401(k) matching"],
#         },
#         {
#             "title": "Barista",
#             "company": "CoffeeHouse",
#             "location": "Portland, OR",
#             "type": "Part-time",
#             "experience_level": "Entry-level",
#             "salary_range": "$15 - $18 per hour",
#             "description": "Prepare coffee and serve customers in a friendly environment.",
#             "requirements": [
#                 "Customer service skills",
#                 "Barista experience (preferred)",
#                 "Positive attitude",
#             ],
#             "benefits": ["Flexible hours", "Employee discount"],
#         },
#         {
#             "title": "UX Researcher",
#             "company": "DesignLabs",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$85,000 - $110,000",
#             "description": "Conduct user research to improve product designs and user experiences.",
#             "requirements": [
#                 "User research methods",
#                 "Interviewing skills",
#                 "Data analysis",
#                 "2+ years experience",
#             ],
#             "benefits": ["Health insurance", "Remote work", "Professional development"],
#         },
#         {
#             "title": "Electrician",
#             "company": "BrightSpark",
#             "location": "Denver, CO",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$50,000 - $75,000",
#             "description": "Install and maintain electrical systems in residential and commercial buildings.",
#             "requirements": [
#                 "Electrician license",
#                 "Experience with electrical systems",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "Paid time off", "401(k)"],
#         },
#         {
#             "title": "Junior Software Engineer",
#             "company": "Innovatech",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Junior",
#             "salary_range": "$70,000 - $90,000",
#             "description": "Assist in the development and maintenance of web applications.",
#             "requirements": [
#                 "Python",
#                 "JavaScript",
#                 "Basic knowledge of React",
#                 "1+ year experience",
#             ],
#             "benefits": ["Health insurance", "401(k) matching", "Remote work"],
#         },
#         {
#             "title": "Product Designer",
#             "company": "CreateSpace",
#             "location": "San Francisco, CA",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$100,000 - $130,000",
#             "description": "Design and prototype new product features based on user needs.",
#             "requirements": [
#                 "Sketch",
#                 "Figma",
#                 "User-centered design principles",
#                 "2+ years experience",
#             ],
#             "benefits": [
#                 "Health insurance",
#                 "Paid vacation",
#                 "Professional development",
#             ],
#         },
#         {
#             "title": "Machine Learning Engineer",
#             "company": "DeepVision AI",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$110,000 - $150,000",
#             "description": "Develop, optimize, and deploy ML models for image and video analytics.",
#             "requirements": [
#                 "Python",
#                 "PyTorch",
#                 "TensorFlow",
#                 "Computer Vision",
#                 "MLOps",
#                 "3+ years experience",
#             ],
#             "benefits": ["Remote work", "Health insurance", "Learning budget"],
#         },
#         {
#             "title": "Software Engineer - Backend",
#             "company": "CloudScale Systems",
#             "location": "Seattle, WA",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$120,000 - $150,000",
#             "description": "Build scalable backend microservices for cloud-native products.",
#             "requirements": [
#                 "Python",
#                 "Go",
#                 "Distributed Systems",
#                 "Docker",
#                 "Kubernetes",
#                 "3+ years experience",
#             ],
#             "benefits": ["Stock options", "401(k)", "Hybrid work"],
#         },
#         {
#             "title": "Data Engineer",
#             "company": "DataForge",
#             "location": "Austin, TX",
#             "type": "Full-time",
#             "experience_level": "Senior",
#             "salary_range": "$140,000 - $175,000",
#             "description": "Design and maintain ETL pipelines and modern data platforms.",
#             "requirements": [
#                 "Python",
#                 "SQL",
#                 "Snowflake",
#                 "Airflow",
#                 "Kafka",
#                 "5+ years experience",
#             ],
#             "benefits": ["Health insurance", "Stock options", "Remote-friendly"],
#         },
#         {
#             "title": "Robotics Software Engineer",
#             "company": "RoboWorks",
#             "location": "Palo Alto, CA",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$130,000 - $160,000",
#             "description": "Develop autonomy and perception software for robotic manipulators.",
#             "requirements": [
#                 "C++",
#                 "ROS2",
#                 "Computer Vision",
#                 "Motion Planning",
#                 "3+ years experience",
#             ],
#             "benefits": ["Equity", "Health insurance", "Onsite gym"],
#         },
#         {
#             "title": "Autonomy Engineer",
#             "company": "AeroNav Robotics",
#             "location": "San Diego, CA",
#             "type": "Full-time",
#             "experience_level": "Senior",
#             "salary_range": "$150,000 - $190,000",
#             "description": "Develop navigation, localization, and control algorithms for autonomous drones.",
#             "requirements": [
#                 "C++",
#                 "Python",
#                 "Kalman Filters",
#                 "SLAM",
#                 "Flight Controls",
#                 "5+ years experience",
#             ],
#             "benefits": ["Health insurance", "Stock options", "Flexible hours"],
#         },
#         {
#             "title": "AI Research Engineer",
#             "company": "Cerebra Labs",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Senior",
#             "salary_range": "$160,000 - $200,000",
#             "description": "Work on cutting-edge research in LLMs, multimodal learning, and generative AI.",
#             "requirements": [
#                 "Python",
#                 "PyTorch",
#                 "Distributed Training",
#                 "Transformers",
#                 "Research experience",
#                 "5+ years experience",
#             ],
#             "benefits": ["Remote work", "Conference budget", "Stock options"],
#         },
#         {
#             "title": "Computer Vision Engineer",
#             "company": "VisionTech Robotics",
#             "location": "Boston, MA",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$115,000 - $150,000",
#             "description": "Build real-time perception pipelines for industrial automation robots.",
#             "requirements": [
#                 "OpenCV",
#                 "C++",
#                 "PyTorch",
#                 "Depth Cameras",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "Paid time off", "Stock plan"],
#         },
#         {
#             "title": "Field Robotics Engineer",
#             "company": "TerraBots",
#             "location": "Denver, CO",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$95,000 - $130,000",
#             "description": "Deploy, test, and troubleshoot autonomous robots in real-world environments.",
#             "requirements": [
#                 "Linux",
#                 "ROS",
#                 "Sensors",
#                 "Electronics debugging",
#                 "2+ years experience",
#             ],
#             "benefits": ["Travel reimbursement", "Health insurance", "401(k)"],
#         },
#         {
#             "title": "Embedded Software Engineer",
#             "company": "MicroSystems",
#             "location": "San Jose, CA",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$120,000 - $150,000",
#             "description": "Develop firmware for microcontrollers in robotics and IoT systems.",
#             "requirements": [
#                 "C",
#                 "C++",
#                 "RTOS",
#                 "SPI/I2C",
#                 "Microcontrollers",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "Onsite lab", "Hybrid work"],
#         },
#         {
#             "title": "ML Ops Engineer",
#             "company": "ScaleFlow",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$125,000 - $160,000",
#             "description": "Build and manage ML pipelines and deployment infrastructure.",
#             "requirements": [
#                 "Docker",
#                 "Kubernetes",
#                 "CI/CD",
#                 "MLflow",
#                 "AWS",
#                 "3+ years experience",
#             ],
#             "benefits": ["Remote work", "Paid vacation", "Hardware budget"],
#         },
#         {
#             "title": "Data Scientist - NLP",
#             "company": "LinguaAI",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Senior",
#             "salary_range": "$155,000 - $185,000",
#             "description": "Develop NLP models including transformers for document understanding.",
#             "requirements": [
#                 "Python",
#                 "Transformers",
#                 "HuggingFace",
#                 "Deep Learning",
#                 "5+ years experience",
#             ],
#             "benefits": ["Remote work", "Stock options", "Conference travel"],
#         },
#         {
#             "title": "Automation Engineer",
#             "company": "FactoryAI",
#             "location": "Detroit, MI",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$100,000 - $130,000",
#             "description": "Automate manufacturing workflows using robotics and vision systems.",
#             "requirements": [
#                 "PLC",
#                 "Robotics",
#                 "Computer Vision",
#                 "C++ or Python",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "Onsite cafeteria", "401(k) match"],
#         },
#         {
#             "title": "Robotics Field Deployment Engineer",
#             "company": "LabMotion",
#             "location": "San Francisco, CA",
#             "type": "Full-time",
#             "experience_level": "Junior",
#             "salary_range": "$80,000 - $110,000",
#             "description": "Deploy robotic automation into biotech and lab environments.",
#             "requirements": [
#                 "Python",
#                 "ROS",
#                 "Troubleshooting",
#                 "Mechanical aptitude",
#                 "1+ year experience",
#             ],
#             "benefits": ["Paid travel", "Health insurance", "Stock options"],
#         },
#         {
#             "title": "SLAM Engineer",
#             "company": "NavBotics",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Senior",
#             "salary_range": "$150,000 - $200,000",
#             "description": "Design SLAM systems for indoor and outdoor autonomous vehicles.",
#             "requirements": [
#                 "C++",
#                 "Sensor Fusion",
#                 "Lidar",
#                 "Visual Odometry",
#                 "5+ years experience",
#             ],
#             "benefits": ["Remote work", "Equity", "Research budget"],
#         },
#         {
#             "title": "Full Stack Engineer",
#             "company": "InsightAI",
#             "location": "New York, NY",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$120,000 - $150,000",
#             "description": "Build full stack dashboards for AI analytics and monitoring.",
#             "requirements": [
#                 "React",
#                 "Node.js",
#                 "Python",
#                 "SQL",
#                 "3+ years experience",
#             ],
#             "benefits": ["Hybrid work", "Health insurance", "401(k)"],
#         },
#         {
#             "title": "Controls Engineer",
#             "company": "MotionForge",
#             "location": "Pittsburgh, PA",
#             "type": "Full-time",
#             "experience_level": "Senior",
#             "salary_range": "$130,000 - $160,000",
#             "description": "Design and tune control systems for mobile robots and manipulators.",
#             "requirements": [
#                 "Control Theory",
#                 "C++",
#                 "ROS",
#                 "MATLAB",
#                 "5+ years experience",
#             ],
#             "benefits": ["Health insurance", "Paid PTO", "Stock plan"],
#         },
#         {
#             "title": "Computer Vision Engineer - Robotics",
#             "company": "AutoVision Robotics",
#             "location": "Chicago, IL",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$115,000 - $150,000",
#             "description": "Develop 3D perception systems using LiDAR, depth cameras, and segmentation.",
#             "requirements": [
#                 "PyTorch",
#                 "OpenCV",
#                 "3D Vision",
#                 "ROS",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "401(k)", "Remote-friendly"],
#         },
#         {
#             "title": "Firmware Engineer",
#             "company": "EmbedTech",
#             "location": "Dallas, TX",
#             "type": "Full-time",
#             "experience_level": "Mid-level",
#             "salary_range": "$110,000 - $140,000",
#             "description": "Develop and optimize firmware for robotics, sensors, and automation hardware.",
#             "requirements": [
#                 "C",
#                 "Embedded Linux",
#                 "I2C/SPI/UART",
#                 "RTOS",
#                 "3+ years experience",
#             ],
#             "benefits": ["Health insurance", "Flexible hours", "Paid training"],
#         },
#         {
#             "title": "Robotics Test Engineer",
#             "company": "ProtoBots",
#             "location": "Los Angeles, CA",
#             "type": "Full-time",
#             "experience_level": "Junior",
#             "salary_range": "$75,000 - $100,000",
#             "description": "Test, validate, and debug robotic systems across hardware and software.",
#             "requirements": [
#                 "Linux",
#                 "Python",
#                 "QA Testing",
#                 "Debugging tools",
#                 "1+ year experience",
#             ],
#             "benefits": ["Health insurance", "Career growth", "401(k)"],
#         },
#         {
#             "title": "Vision Systems Engineer",
#             "company": "OptiScan",
#             "location": "Remote",
#             "type": "Full-time",
#             "experience_level": "Senior",
#             "salary_range": "$140,000 - $180,000",
#             "description": "Design high-speed vision systems for automated inspection.",
#             "requirements": [
#                 "C++",
#                 "OpenCV",
#                 "Image Processing",
#                 "Cameras/Lighting",
#                 "5+ years experience",
#             ],
#             "benefits": ["Remote work", "Conference budget", "Health insurance"],
# }]

    jobs = [
        {
            "title": "AI Research Scientist",
            "company": "Cerebra Labs",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Senior",
            "salary_range": "$160,000 - $200,000",
            "description": "Conduct cutting-edge AI research and develop novel ML algorithms.",
            "requirements": ["Python", "PyTorch", "Deep Learning", "Research experience", "5+ years experience"],
            "benefits": ["Remote work", "Conference budget", "Stock options"],
        },
        {
            "title": "Deep Learning Engineer",
            "company": "VisionTech AI",
            "location": "San Francisco, CA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$130,000 - $160,000",
            "description": "Develop and optimize deep learning models for image and video analytics.",
            "requirements": ["Python", "PyTorch", "TensorFlow", "3+ years experience"],
            "benefits": ["Health insurance", "Remote work", "Learning budget"],
        },
        {
            "title": "NLP Engineer",
            "company": "LinguaAI",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $150,000",
            "description": "Build NLP models for text understanding and conversational AI.",
            "requirements": ["Python", "Transformers", "HuggingFace", "Deep Learning", "3+ years experience"],
            "benefits": ["Remote work", "Stock options", "Conference travel"],
        },
        {
            "title": "AI Solutions Architect",
            "company": "TechCorp",
            "location": "New York, NY",
            "type": "Full-time",
            "experience_level": "Senior",
            "salary_range": "$150,000 - $190,000",
            "description": "Design AI solutions and architecture for enterprise-scale applications.",
            "requirements": ["Python", "Cloud platforms", "ML deployment", "5+ years experience"],
            "benefits": ["Health insurance", "401(k) matching", "Remote work"],
        },
        {
            "title": "Computer Vision Engineer - AI",
            "company": "AutoVision",
            "location": "Boston, MA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$115,000 - $150,000",
            "description": "Develop real-time computer vision pipelines for AI applications.",
            "requirements": ["Python", "OpenCV", "PyTorch", "3+ years experience"],
            "benefits": ["Health insurance", "Paid time off", "Stock options"],
        },
        {
            "title": "AI Product Manager",
            "company": "NextGen AI",
            "location": "San Francisco, CA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$130,000 - $160,000",
            "description": "Manage product roadmap for AI-powered applications.",
            "requirements": ["Product Management", "AI/ML knowledge", "3+ years experience"],
            "benefits": ["Health insurance", "Stock options", "Flexible hours"],
        },
        {
            "title": "AI Infrastructure Engineer",
            "company": "CloudAI",
            "location": "Seattle, WA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $150,000",
            "description": "Build scalable AI infrastructure for training and deployment.",
            "requirements": ["Python", "Docker", "Kubernetes", "Cloud", "3+ years experience"],
            "benefits": ["Remote work", "Stock options", "Learning budget"],
        },
        {
            "title": "Applied Data Scientist - AI",
            "company": "DataSolve",
            "location": "New York, NY",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $145,000",
            "description": "Apply ML/AI techniques to solve business problems.",
            "requirements": ["Python", "SQL", "Machine Learning", "Statistics", "3+ years experience"],
            "benefits": ["Health insurance", "Stock options", "Flexible hours"],
        },
        {
            "title": "AI Ethics Specialist",
            "company": "EthicalAI",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Senior",
            "salary_range": "$130,000 - $170,000",
            "description": "Ensure ethical AI practices and compliance across projects.",
            "requirements": ["AI knowledge", "Policy experience", "3+ years experience"],
            "benefits": ["Remote work", "Conference budget", "Health insurance"],
        },
        {
            "title": "Machine Learning Engineer",
            "company": "DeepVision AI",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$110,000 - $150,000",
            "description": "Develop, optimize, and deploy ML models for image and video analytics.",
            "requirements": ["Python", "PyTorch", "TensorFlow", "Computer Vision", "MLOps", "3+ years experience"],
            "benefits": ["Remote work", "Health insurance", "Learning budget"],
        },

        {
            "title": "Software Development Engineer",
            "company": "CloudScale Systems",
            "location": "Seattle, WA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $150,000",
            "description": "Develop backend services and APIs for cloud-native applications.",
            "requirements": ["Python", "Go", "Docker", "Kubernetes", "3+ years experience"],
            "benefits": ["Stock options", "401(k)", "Hybrid work"],
        },
        {
            "title": "Frontend Developer",
            "company": "WebTech",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$90,000 - $130,000",
            "description": "Build interactive frontend applications with React and TypeScript.",
            "requirements": ["JavaScript", "React", "TypeScript", "CSS", "3+ years experience"],
            "benefits": ["Health insurance", "Remote work", "Professional development"],
        },
        {
            "title": "Full Stack Developer",
            "company": "InsightAI",
            "location": "New York, NY",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $150,000",
            "description": "Develop full-stack applications for AI analytics dashboards.",
            "requirements": ["React", "Node.js", "Python", "SQL", "3+ years experience"],
            "benefits": ["Hybrid work", "Health insurance", "401(k)"],
        },
        {
            "title": "Backend Developer",
            "company": "Innovatech",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Junior",
            "salary_range": "$70,000 - $90,000",
            "description": "Support development of scalable backend services.",
            "requirements": ["Python", "SQL", "Basic API knowledge", "1+ year experience"],
            "benefits": ["Health insurance", "401(k) matching", "Remote work"],
        },
        {
            "title": "Mobile App Developer",
            "company": "Appify",
            "location": "Austin, TX",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$100,000 - $135,000",
            "description": "Develop mobile applications for iOS and Android.",
            "requirements": ["Swift", "Kotlin", "React Native", "3+ years experience"],
            "benefits": ["Health insurance", "Remote work", "Learning budget"],
        },
        {
            "title": "DevOps Engineer",
            "company": "ScaleFlow",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $150,000",
            "description": "Maintain CI/CD pipelines and cloud infrastructure.",
            "requirements": ["AWS", "Docker", "Kubernetes", "Terraform", "3+ years experience"],
            "benefits": ["Remote work", "Stock options", "Hardware budget"],
        },
        {
            "title": "Cloud Software Engineer",
            "company": "NextCloud",
            "location": "San Francisco, CA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$125,000 - $155,000",
            "description": "Develop scalable cloud-native applications and microservices.",
            "requirements": ["Python", "AWS", "Docker", "Kubernetes", "3+ years experience"],
            "benefits": ["Health insurance", "401(k)", "Remote work"],
        },
        {
            "title": "Junior Software Engineer",
            "company": "Innovatech",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Junior",
            "salary_range": "$70,000 - $90,000",
            "description": "Assist in the development and maintenance of web applications.",
            "requirements": ["Python", "JavaScript", "Basic knowledge of React", "1+ year experience"],
            "benefits": ["Health insurance", "401(k) matching", "Remote work"],
        },
        {
            "title": "SDE Intern",
            "company": "TechStart",
            "location": "Boston, MA",
            "type": "Internship",
            "experience_level": "Intern",
            "salary_range": "$30/hour",
            "description": "Support software development teams with coding and testing tasks.",
            "requirements": ["Python", "JavaScript", "Basic understanding of CS concepts"],
            "benefits": ["Stipend", "Mentorship", "Flexible hours"],
        },
        {
            "title": "Frontend Intern",
            "company": "DesignLabs",
            "location": "Remote",
            "type": "Internship",
            "experience_level": "Intern",
            "salary_range": "$25/hour",
            "description": "Assist in building frontend UI components and styling.",
            "requirements": ["HTML", "CSS", "JavaScript", "React basics"],
            "benefits": ["Remote work", "Learning budget", "Mentorship"],
        },

        {
            "title": "TA - AI & ML",
            "company": "CMU",
            "location": "Pittsburgh, PA",
            "type": "Part-time",
            "experience_level": "Entry-level",
            "salary_range": "$25,000 - $35,000",
            "description": "Assist in teaching AI & ML courses, grading, and student support.",
            "requirements": ["Python", "ML knowledge", "Communication skills", "1+ year experience"],
            "benefits": ["Flexible hours", "Campus access"],
        },
        {
            "title": "TA - Robotics",
            "company": "CMU",
            "location": "Pittsburgh, PA",
            "type": "Part-time",
            "experience_level": "Entry-level",
            "salary_range": "$25,000 - $35,000",
            "description": "Assist in teaching Robotics courses and lab sessions.",
            "requirements": ["Python", "ROS", "Mechanical knowledge", "1+ year experience"],
            "benefits": ["Flexible hours", "Campus access"],
        },

        {
            "title": "Data Scientist",
            "company": "DataCo",
            "location": "New York, NY",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$100,000 - $140,000",
            "description": "Build and deploy machine learning models for predictive analytics.",
            "requirements": ["Python", "SQL", "Machine Learning", "Statistics", "3+ years experience"],
            "benefits": ["Health insurance", "Stock options", "Flexible hours"],
        },
        {
            "title": "Senior Data Scientist",
            "company": "AnalyticsPro",
            "location": "Chicago, IL",
            "type": "Full-time",
            "experience_level": "Senior",
            "salary_range": "$140,000 - $180,000",
            "description": "Lead advanced analytics projects and mentor junior data scientists.",
            "requirements": ["Python", "R", "SQL", "Machine Learning", "5+ years experience"],
            "benefits": ["Health insurance", "Stock options", "Flexible hours"],
        },
        {
            "title": "NLP Data Scientist",
            "company": "LinguaTech",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $150,000",
            "description": "Develop NLP models for document understanding and text analytics.",
            "requirements": ["Python", "Transformers", "HuggingFace", "3+ years experience"],
            "benefits": ["Remote work", "Stock options", "Conference travel"],
        },
        {
            "title": "Computer Vision Data Scientist",
            "company": "VisionAI",
            "location": "San Francisco, CA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$125,000 - $160,000",
            "description": "Build CV models for image and video analysis pipelines.",
            "requirements": ["Python", "PyTorch", "OpenCV", "3+ years experience"],
            "benefits": ["Health insurance", "Remote work", "Learning budget"],
        },
        {
            "title": "Data Scientist - Healthcare",
            "company": "HealthAnalytics",
            "location": "Boston, MA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $150,000",
            "description": "Analyze healthcare datasets to develop predictive models.",
            "requirements": ["Python", "SQL", "Machine Learning", "Statistics", "3+ years experience"],
            "benefits": ["Health insurance", "Stock options", "Flexible hours"],
        },
        {
            "title": "Junior Data Scientist",
            "company": "DataStart",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Junior",
            "salary_range": "$75,000 - $95,000",
            "description": "Support data analysis and ML model development under senior guidance.",
            "requirements": ["Python", "SQL", "Basic ML knowledge", "1+ year experience"],
            "benefits": ["Remote work", "Health insurance", "Mentorship"],
        },

        {
            "title": "Data Engineer",
            "company": "DataForge",
            "location": "Austin, TX",
            "type": "Full-time",
            "experience_level": "Senior",
            "salary_range": "$140,000 - $175,000",
            "description": "Design and maintain ETL pipelines and modern data platforms.",
            "requirements": ["Python", "SQL", "Snowflake", "Airflow", "Kafka", "5+ years experience"],
            "benefits": ["Health insurance", "Stock options", "Remote-friendly"],
        },
        {
            "title": "ETL Developer",
            "company": "AnalyticsPro",
            "location": "Chicago, IL",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$110,000 - $135,000",
            "description": "Develop and maintain ETL workflows and data pipelines.",
            "requirements": ["Python", "SQL", "Airflow", "3+ years experience"],
            "benefits": ["Health insurance", "Remote work", "Learning budget"],
        },
        {
            "title": "Big Data Engineer",
            "company": "BigDataWorks",
            "location": "New York, NY",
            "type": "Full-time",
            "experience_level": "Senior",
            "salary_range": "$145,000 - $180,000",
            "description": "Build and optimize Hadoop/Spark pipelines for large-scale data processing.",
            "requirements": ["Python", "Spark", "Hadoop", "SQL", "5+ years experience"],
            "benefits": ["Stock options", "Health insurance", "Flexible hours"],
        },
        {
            "title": "Junior Data Engineer",
            "company": "DataStart",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Junior",
            "salary_range": "$75,000 - $95,000",
            "description": "Support ETL pipelines and data platform maintenance.",
            "requirements": ["Python", "SQL", "1+ year experience"],
            "benefits": ["Remote work", "Mentorship", "Health insurance"],
        },
        {
            "title": "Cloud Data Engineer",
            "company": "CloudData Inc.",
            "location": "Seattle, WA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$125,000 - $155,000",
            "description": "Build scalable data pipelines in cloud environments.",
            "requirements": ["Python", "AWS", "SQL", "Airflow", "3+ years experience"],
            "benefits": ["Remote work", "Stock options", "Learning budget"],
        },

        {
            "title": "IoT Software Engineer",
            "company": "SmartHome Inc.",
            "location": "Austin, TX",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$110,000 - $140,000",
            "description": "Develop firmware and applications for IoT devices.",
            "requirements": ["C/C++", "Python", "MQTT", "3+ years experience"],
            "benefits": ["Health insurance", "Remote work", "Learning budget"],
        },
        {   
            "title": "Embedded IoT Engineer",
            "company": "ConnectedDevices",
            "location": "San Jose, CA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$115,000 - $145,000",
            "description": "Develop firmware for IoT devices and connected systems.",
            "requirements": ["C", "C++", "RTOS", "Embedded Linux", "3+ years experience"],
            "benefits": ["Health insurance", "Hybrid work", "Learning budget"],
        },
        {
            "title": "IoT Cloud Engineer",
            "company": "IoTCloudTech",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $150,000",
            "description": "Develop and maintain cloud services for IoT ecosystems.",
            "requirements": ["Python", "AWS IoT", "MQTT", "Docker", "3+ years experience"],
            "benefits": ["Remote work", "Health insurance", "Stock options"],
        },
        {
            "title": "IoT Security Engineer",
            "company": "SecureIoT",
            "location": "San Diego, CA",
            "type": "Full-time",
            "experience_level": "Senior",
            "salary_range": "$130,000 - $165,000",
            "description": "Design and implement security protocols for IoT devices and networks.",
            "requirements": ["Cybersecurity", "Embedded Systems", "IoT Protocols", "5+ years experience"],
            "benefits": ["Health insurance", "Stock options", "Flexible hours"],
        },
        {
            "title": "IoT Analytics Engineer",
            "company": "SmartAnalytics",
            "location": "Boston, MA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$115,000 - $145,000",
            "description": "Analyze data from IoT devices to generate actionable insights.",
            "requirements": ["Python", "SQL", "IoT data pipelines", "3+ years experience"],
            "benefits": ["Health insurance", "Remote-friendly", "Professional development"],
        },
        {
            "title": "LLM Engineer",
            "company": "Cerebra Labs",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Senior",
            "salary_range": "$160,000 - $200,000",
            "description": "Develop, fine-tune, and deploy large language models at scale.",
            "requirements": ["Python", "PyTorch", "Transformers", "MLOps", "5+ years experience"],
            "benefits": ["Remote work", "Stock options", "Conference budget"],
        },
        {
            "title": "LLM Research Engineer",
            "company": "NextGen AI",
            "location": "San Francisco, CA",
            "type": "Full-time",
            "experience_level": "Senior",
            "salary_range": "$155,000 - $195,000",
            "description": "Conduct research and develop large language models for NLP tasks.",
            "requirements": ["Python", "PyTorch", "Deep Learning", "Transformers", "5+ years experience"],
            "benefits": ["Health insurance", "Remote-friendly", "Learning budget"],
        },
        {
            "title": "LLM Deployment Engineer",
            "company": "ScaleFlow",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$130,000 - $160,000",
            "description": "Deploy and monitor LLMs on cloud infrastructure.",
            "requirements": ["Python", "MLOps", "Docker", "Kubernetes", "3+ years experience"],
            "benefits": ["Remote work", "Stock options", "Hardware budget"],
        },
        {
            "title": "LLM NLP Engineer",
            "company": "LinguaAI",
            "location": "Remote",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $150,000",
            "description": "Develop NLP models and fine-tune LLMs for domain-specific tasks.",
            "requirements": ["Python", "Transformers", "HuggingFace", "Deep Learning", "3+ years experience"],
            "benefits": ["Remote work", "Stock options", "Flexible hours"],
        },

        {
            "title": "Robotics Software Engineer",
            "company": "RoboWorks",
            "location": "Palo Alto, CA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$130,000 - $160,000",
            "description": "Develop autonomy and perception software for robotic manipulators.",
            "requirements": ["C++", "ROS2", "Computer Vision", "Motion Planning", "3+ years experience"],
            "benefits": ["Equity", "Health insurance", "Onsite gym"],
        },
        {
            "title": "Autonomy Engineer",
            "company": "AeroNav Robotics",
            "location": "San Diego, CA",
            "type": "Full-time",
            "experience_level": "Senior",
            "salary_range": "$150,000 - $190,000",
            "description": "Develop navigation, localization, and control algorithms for autonomous drones.",
            "requirements": ["C++", "Python", "Kalman Filters", "SLAM", "Flight Controls", "5+ years experience"],
            "benefits": ["Health insurance", "Stock options", "Flexible hours"],
        },
        {
            "title": "Field Robotics Engineer",
            "company": "TerraBots",
            "location": "Denver, CO",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$95,000 - $130,000",
            "description": "Deploy, test, and troubleshoot autonomous robots in real-world environments.",
            "requirements": ["Linux", "ROS", "Sensors", "Electronics debugging", "2+ years experience"],
            "benefits": ["Travel reimbursement", "Health insurance", "401(k)"],
        },
        {
            "title": "Embedded Robotics Engineer",
            "company": "MicroSystems",
            "location": "San Jose, CA",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$120,000 - $150,000",
            "description": "Develop firmware for robotic and IoT systems.",
            "requirements": ["C", "C++", "RTOS", "SPI/I2C", "3+ years experience"],
            "benefits": ["Health insurance", "Onsite lab", "Hybrid work"],
        },
        {
            "title": "Computer Vision Engineer - Robotics",
            "company": "AutoVision Robotics",
            "location": "Chicago, IL",
            "type": "Full-time",
            "experience_level": "Mid-level",
            "salary_range": "$115,000 - $150,000",
            "description": "Develop 3D perception systems for autonomous robots using LiDAR and cameras.",
            "requirements": ["PyTorch", "OpenCV", "3D Vision", "ROS", "3+ years experience"],
            "benefits": ["Health insurance", "401(k)", "Remote-friendly"],
        },
    ]
    
    for job in jobs:
        db.add_job(job)

    print(len(jobs))

    print("Database seeded successfully!")


if __name__ == "__main__":
    seed_jobs()